{:@, [line: 18],
  [{:spec, [line: 18],
    [{:::, [line: 18],
      [{:fun_default, [line: 18], [{:any, [line: 18], []}]}, nil]}]}]}

{:@, [line: 20],
  [{:spec, [line: 20],
    [{:::, [line: 20], [{:simple, [line: 20], []}, nil]}]}]}


{{:trim_trailing, 2},
 {:type, 813, :fun,
  [{:type, 813, :product,
    [{:user_type, 813, :t, []}, {:user_type, 813, :t, []}]},
   {:user_type, 813, :t, []}]}, []}

{{:replace, 4},
 {:type, 1028, :fun,
  [{:type, 1028, :product,
    [{:user_type, 1028, :t, []},
     {:type, 1028, :union,
      [{:user_type, 1028, :pattern, []},
       {:remote_type, 1028, [{:atom, 0, Regex}, {:atom, 0, :t}, []]}]},
     {:user_type, 1028, :t, []},
     {:remote_type, 1028, [{:atom, 0, Keyword}, {:atom, 0, :t}, []]}]},
   {:user_type, 1028, :t, []}]}, []}

[{:replace, [line: 40],
 [{:t, [line: 40], nil},
  {:|, [line: 40],
   [{:pattern, [line: 40], nil},
    {{:., [line: 40],
      [{:__aliases__, [counter: 0, line: 40], [:Regex]}, :t]},
     [line: 40], []}]}, {:t, [line: 40], nil},
  {{:., [line: 40],
    [{:__aliases__, [counter: 0, line: 40], [:Keyword]}, :t]},
   [line: 40], []}]}, {:t, [line: 40], nil}]}]}]}


{:@, [line: 40],
  [{:spec, [line: 40],
    [{:::, [line: 40],
      [{:replace, [line: 40],
        [{:t, [line: 40], nil},
         {:|, [line: 40],
          [{:pattern, [line: 40], nil},
           {{:., [line: 40],
             [{:__aliases__, [counter: 0, line: 40], [:Regex]}, :t]},
            [line: 40], []}]}, {:t, [line: 40], nil},
         {{:., [line: 40],
           [{:__aliases__, [counter: 0, line: 40], [:Keyword]}, :t]},
          [line: 40], []}]}, {:t, [line: 40], nil}]}]}]}

%{opaques: [{:t, {:atom, 0, nil}, []}],
  specs: [{{:__info__, 1},
    [{:type, 10, :fun,
      [{:type, 10, :product,
        [{:type, 10, :union,
          [{:atom, 10, :attributes}, {:atom, 10, :compile},
           {:atom, 10, :exports}, {:atom, 10, :functions}, {:atom, 10, :macros},
           {:atom, 10, :md5}, {:atom, 10, :module},
           {:atom, 10, :native_addresses}]}]},
       {:type, 10, :union,
        [{:type, 10, :atom, []},
         {:type, 10, :list,
          [{:type, 10, :union,
            [{:type, 10, :tuple,
              [{:type, 10, :atom, []}, {:type, 10, :any, []}]},
             {:type, 10, :tuple,
              [{:type, 10, :atom, []}, {:type, 10, :byte, []},
               {:type, 10, :integer, []}]}]}]}]}]}]},
   {{:replace, 4},
    [{:type, 40, :fun,
      [{:type, 40, :product,
        [{:user_type, 40, :t, []},
         {:type, 40, :union,
          [{:user_type, 40, :pattern, []},
           {:remote_type, 40, [{:atom, 0, Regex}, {:atom, 0, :t}, []]}]},
         {:user_type, 40, :t, []},
         {:remote_type, 40, [{:atom, 0, Keyword}, {:atom, 0, :t}, []]}]},
       {:user_type, 40, :t, []}]}]},
   {{:fun_default, 1},
    [{:type, 18, :fun,
      [{:type, 18, :product, [{:type, 18, :any, []}]}, {:atom, 0, nil}]}]},
   {{:fun_default, 0},
    [{:type, 17, :fun, [{:type, 17, :product, []}, {:atom, 0, nil}]}]},
   {{:hello, 1},
    [{:type, 23, :fun,
      [{:type, 23, :product, [{:user_type, 23, :test_type, []}]},
       {:type, 23, :union,
        [{:user_type, 23, :test_type, []},
         {:remote_type, 23, [{:atom, 0, Map}, {:atom, 0, :t}, []]}]}]}]},
   {{:simple, 0},
    [{:type, 20, :fun, [{:type, 20, :product, []}, {:atom, 0, nil}]}]}],
  types: [{:pattern, {:atom, 0, nil}, []},
   {:test_type, {:remote_type, 15, [{:atom, 0, String}, {:atom, 0, :t}, []]},
    []}]}
